### ISSUE TITLE
request more robust behavior in read-only directories

### ISSUE THREAD

**Issue by dkoes** [pysb/pysb#178]
PySB can't do its thing (at least its BNG thing) if it doesn't have write access to the current directory. This is an issue if you are running PySB within a cgi script where you don't want the webserver to have write access.

My suggestions is to change directories into a temporary directory before opening files in generate_network.  For example, around line 247 of bng.py:
```
    os.chdir('/tmp/')
    bng_filename = '%s_%d_%d_temp.bngl' % (model.name, os.getpid(), random.randint(0, 10000))
```
Of course, it would be better programming practice to use python's tmpfile.mkdtemp.

**Comment by jmuhlich** [comment]
Thanks for pointing this out. `mkdtemp` is the perfect solution as it transparently handles the cross-platform issues around finding a writeable temp directory.

**Comment by alubbock** [comment]
I think the recently merged BNG interface classes - `BngConsole` and `BngFileInterface` - handle this already. I used `tempfile.NamedTemporaryFile()` to generate the BNGL file in that code. The location of that BNGL file is then supplied as the current working directory to BNG. This should ensure the location is writeable, no?

**Comment by dkoes** [comment]
The code is in pysb, not bng.. I'm using a recent checkout of pysb from git.

**Comment by jmuhlich** [comment]
Yes, @alubbock means the code in pysb that talks to bng. How recent is your checkout, @dkoes ? The code in question was only merged 2 weeks ago.

@alubbock however this brings up a good point: For security reasons, it's probably best to have BNG write all its temp files in a single locked-down subdirectory rather than in a world-readable temp directory. `mkdtemp` would provide that.

**Comment by dkoes** [comment]
You're right, that commit resolved the issue.  Sorry, should have git pulled first.
