### ISSUE TITLE
Unit tests fail with latest Kappa

### ISSUE THREAD

**Issue by alubbock** [pysb/pysb#193]
The PySB unit tests fail with the latest Kappa at time of writing (commit https://github.com/Kappa-Dev/KaSim/commit/9c4b41905123055be4c5334c08744e27de6828b8).

Several "no such file or directory" errors appear, similar to the one below for "Test generation of contact map by run_static_analysis":

> IOError: [Errno 2] No such file or directory: './tmpKappa_test_run_static_analysis_cmap_IWNEqj/test_run_static_analysis_cmap_cm.dot'

Example travis log: https://travis-ci.org/LoLab-VU/pysb/jobs/118849210

Perhaps we should test against a release version of Kappa rather than their master branch, which is probably a too rapidly moving target?

**Comment by johnbachman** [comment]
Argh. There's no release version of KaSim 4 yet, and stuff doesn't work if you use the tagged "last-KaSim3" (which is what I was using for testing for a while until I started running into errors). Perhaps for the time being we could use a commit from when the Kappa pull request was merged, since things worked then?

**Comment by alubbock** [comment]
Agree - the Kappa commit from when your PR #188 was merged is https://github.com/Kappa-Dev/KaSim/commit/f87eada74a188dc14eabfbe43f8e264cd5352a6a. I'll add a `git checkout` to the travis config now.

**Comment by johnbachman** [comment]
Thanks!
