### ISSUE TITLE
Error in ScipyOdeSimulator with models that have synthesis rules

### ISSUE THREAD

**Issue by ortega2247** [pysb/pysb#316]
When a model have a synthesis rule, there is an initial condition that is created during the network generation. Hence, when I pass the param_values argument to ScipyOdeSimulator it raises a problem because of that new initial condition that is being created. This reproduces the error:

`from pysb.examples.tyson_oscillator import model`
`from pysb.simulator.scipyode import ScipyOdeSimulator`
`parameters = [par.value for par in model.parameters]`
`sim = ScipyOdeSimulator(model, tspan= [1,2,3,4,5], param_values = parameters)`

**Comment by alubbock** [comment]
Hi Oscar, this is not strictly an issue with the simulator itself, but an issue with the way PySB creates a dummy parameter `__source_0` when the model's reaction network is generated (which happens when `ScipyOdeSimulator` is instantiated in the above example). This means your `parameters` list is one entry too short.

The simplest workaround is to run `model.enable_synth_deg()` before accessing `model.parameters` (`pysb.bng.generate_equations()` works too).

Alternatively, you could structure `parameters` as a dictionary:

`parameters = {p.name: p.value for p in model.parameters}`

We (PySB developers) should think about the best way to address this, but it will mean internal changes that we should discuss. Hopefully the above alternatives will work for you until we find a solution. Perhaps hiding the dummy parameter and the dummy monomers (`__source` and `__sink`) from view would make sense. Thoughts @jmuhlich @lh64 ?

Note for others: on PySB 1.5.0, the error is actually raised on `sim.run()`, which gives an `IndexError`.

**Comment by lh64** [comment]
The best solution is to eliminate the `__source` and `__sink` species and replace them with BNG's null symbol `0`. That will probably take some work though. This is actually discussed in issue #10 of our fork (https://github.com/LoLab-VU/pysb/issues/10).
