### ISSUE TITLE
reaction rate constants dependending on the concentrations of products from other reactions

### ISSUE THREAD

**Issue by rribeiro-pt** [pysb/pysb#330]
Hello everyone,
I am assembling a metabolic pathway, in which the reaction rate constants of some reactions are dependent on the concentrations of products from other reactions. How can I include the concentration of those products on reaction rate constants?

Thank you in advance.

**Comment by glucksfall** [comment]
Hello,

I'm not part of the dev team, but I'm interested in modeling metabolism. At the moment, I'm not considering the product of any other reaction as part of the reaction rate and I think you want to include it because that product is an activator or an inhibitor of the reaction, am I right?

Either case, I think you need to create a Variable() that measure the product quantity (or the concentration if you know the volume of your reactor) and use that variable to build up and Expression() for the rate. If that fails, I would prefer to export the model to your preferred language and modify the file (I do that to add tokens into rules in kappa language, and it easy to do the same to rate because KaSim allows the use of algebraic expressions in rates)

Regards!

**Comment by alubbock** [comment]
@rribeiro-pt Yes, this is possible. PySB has a special entity for non-mass action rates, called Expressions. Expressions can be used in place of Parameters for rule rates. Expressions can (in theory) be any valid [sympy](http://sympy.org) expression, and can utilize other Expressions, Parameters, and Observables. Here’s a contrived example for demonstration purposes:

```python
Parameter('A_multiplier', 2.0)
Observable('A_total', A())
Expression('kf_A', A_total * A_multiplier)
Rule('bindA', A(b=None) + A(b=None) >> A(b=1) % A(b=1), kf_A)
```

**Comment by rribeiro-pt** [comment]
Hi! 
Thank you very much for your help. Now, my metabolic pathway runs smoothly.

Best regards!!

**Comment by alubbock** [comment]
Glad I could help. I'll close this issue.

If you have any further questions about PySB, feel free to ask in our [chat room on gitter](https://gitter.im/pysb/pysb).

Thanks!
