### ISSUE TITLE
TypeError when using reversible rule operator

### ISSUE THREAD

**Issue by ryants** [pysb/pysb#342]
The reversible rule operator `|` does not seem to work.  The following model results in a TypeError being raised:

    Model()
    Monomer('A', ['bind'])
    Monomer('B', ['bind'])
    Parameter('k', 1)
    Rule('bind', A(bind=None) + B(bind=None) | A(bind=1) % B(bind=1), k, k)

The specific error is:
``TypeError: unsupported operand type(s) for |: 'ReactionPattern' and 'ComplexPattern'``

**Comment by alubbock** [comment]
Please could you confirm the version of Python and PySB you're using? I was unable to reproduce your error on either Python 2.7.14 or Python 3.5.2 using the current PySB master (commit c55f3a5).

You can check the PySB version with `print(pysb.__version__)`.

**Comment by ryants** [comment]
Python 3.6.1 and pysb v1.5.0

**Comment by alubbock** [comment]
PySB v1.5.0 is the latest release version, but the `|` reversible rule operator was only recently added to PySB on Github. It will be present in the next release.

If you want to use `|` in the meantime, you'll need to use a pre-release version of PySB from Github (e.g. `pip install git+git://github.com/pysb/pysb.git`). I'll speak to other admins about getting a release out ASAP so that our users can begin switching to the new syntax.

**Comment by ryants** [comment]
Ah, ok.  It was in the docs, so I figured it was in the latest release

Thanks!

**Comment by alubbock** [comment]
PySB v1.6.0 has now been released, which includes the `|` reversible rule operator. We've also updated [pysb.readthedocs.org](http://pysb.readthedocs.org) to reflect the most recent release by default, rather than development version, to avoid such confusion in the future.
