### ISSUE TITLE
Rule without initial condition raises problem with generate_network()

### ISSUE THREAD

**Issue by glucksfall** [pysb/pysb#472]
Hello everyone,

I found a weird problem when calling the generate_network(). I declared a non-reversible rule, but I didn't set an initial condition for the LHS (meaning the rule could never execute). Then, I called generate_network() and the error was:

```
---------------------------------------------------------------------------
BngInterfaceError                         Traceback (most recent call last)
<ipython-input-5-a23f3307d273> in <module>
      1 set_path('bng', '/shared/D1/opt/git-repositories/bionetgen.RuleWorld/bng2/')
----> 2 generate_network(model)
      3 generate_equations(model)
      4 sim_result = ScipyOdeSimulator(model, linspace(0, 40, 100)).run()

/usr/local/lib/python3.6/dist-packages/pysb/bng.py in generate_network(model, cleanup, append_stdout, verbose, **kwargs)
    669         bngfile.action('generate_network', overwrite=True,
    670                        verbose=bng_action_debug, **kwargs)
--> 671         bngfile.execute()
    672 
    673         output = bngfile.read_netfile()

/usr/local/lib/python3.6/dist-packages/pysb/bng.py in execute(self, reload_netfile, skip_file_actions)
    484         if p.returncode or captured_error_lines:
    485             raise BngInterfaceError('\n'.join(captured_error_lines) + "\n" +
--> 486                                     p_err.rstrip())
    487 
    488     def action(self, action, **kwargs):

BngInterfaceError: 
ABORT: writeFile() was asked to write the network, but no reactions were found.
Did you remember to call generate_network() before writing network output?

  at line 28
```

The generate_network() works as expected when I make reversible the reaction (because I declared an initial amount for the RHS).

I don't know if there's a way to make more informative the error message. At least, I didn't forget to call generate_network()...

Best regards

**Comment by lh64** [comment]
Hi @glucksfall. The error message that you're seeing is actually coming from BNG, not PySB. So it's not the same `generate_network()` method. As I think you've figured out, the problem you're having is because you don't have any `Initials` (`seed species` in BNG language) defined, so BNG isn't generating any reactions. When it tries to output the network to file (which PySB will then read in), there's nothing there so it throws the error message you're seeing. I understand that the error message is a bit confusing because not calling `generate_network()` is not the problem. I've modified the error message in the BNG code to read:
`"writeFile() was asked to write the network, but no reactions were found.\n"
                  ."Did you remember to call generate_network() or to define seed species before writing network output?\n";`
(You can see the change here: https://github.com/RuleWorld/bionetgen/commit/926cee296b7550617a8bdeda410bd2d247c1fa30)
It may take some time for the next BNG release to come out with that change but at least you know what the issue is now. Thanks for raising it with us, it helps a lot to know what issues users are running into. If you have any questions, just let me know. --Leonard
